/* 
	Name: Props-Insight script tracking 
	Author: NHATVD
	Version : v2.1
	LastUpdate: 15:44 18/04/2017
*/
"object"!==typeof JSON2&&(JSON2={});
(function(){function b(b){return 10>b?"0"+b:b}function e(b){d.lastIndex=0;return d.test(b)?'"'+b.replace(d,function(b){var c=m[b];return"string"===typeof c?c:"\\u"+("0000"+b.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+b+'"'}function c(d,f){var p,m,w,z,q=g,v,r=f[d];r&&"object"===typeof r&&(p=r,w=Object.prototype.toString.apply(p),r="[object Date]"===w?isFinite(p.valueOf())?p.getUTCFullYear()+"-"+b(p.getUTCMonth()+1)+"-"+b(p.getUTCDate())+"T"+b(p.getUTCHours())+":"+b(p.getUTCMinutes())+":"+b(p.getUTCSeconds())+
"Z":null:"[object String]"===w||"[object Number]"===w||"[object Boolean]"===w?p.valueOf():"[object Array]"!==w&&"function"===typeof p.toJSON?p.toJSON(d):p);"function"===typeof x&&(r=x.call(f,d,r));switch(typeof r){case "string":return e(r);case "number":return isFinite(r)?String(r):"null";case "boolean":case "null":return String(r);case "object":if(!r)return"null";g+=u;v=[];if("[object Array]"===Object.prototype.toString.apply(r)){z=r.length;for(p=0;p<z;p+=1)v[p]=c(p,r)||"null";w=0===v.length?"[]":
g?"[\n"+g+v.join(",\n"+g)+"\n"+q+"]":"["+v.join(",")+"]";g=q;return w}if(x&&"object"===typeof x)for(z=x.length,p=0;p<z;p+=1)"string"===typeof x[p]&&(m=x[p],(w=c(m,r))&&v.push(e(m)+(g?": ":":")+w));else for(m in r)Object.prototype.hasOwnProperty.call(r,m)&&(w=c(m,r))&&v.push(e(m)+(g?": ":":")+w);w=0===v.length?"{}":g?"{\n"+g+v.join(",\n"+g)+"\n"+q+"}":"{"+v.join(",")+"}";g=q;return w}}var f=RegExp("[\x00\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]",
"g"),d=RegExp('[\\\\\\"\x00-\u001f\u007f-\u009f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]',"g"),g,u,m={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},x;"function"!==typeof JSON2.stringify&&(JSON2.stringify=function(b,d,e){var f;u=g="";if("number"===typeof e)for(f=0;f<e;f+=1)u+=" ";else"string"===typeof e&&(u=e);if((x=d)&&"function"!==typeof d&&("object"!==typeof d||"number"!==typeof d.length))throw Error("JSON2.stringify");
return c("",{"":b})});"function"!==typeof JSON2.parse&&(JSON2.parse=function(b,c){function d(b,e){var f,g,r=b[e];if(r&&"object"===typeof r)for(f in r)Object.prototype.hasOwnProperty.call(r,f)&&(g=d(r,f),void 0!==g?r[f]=g:delete r[f]);return c.call(b,e,r)}var e;b=String(b);f.lastIndex=0;f.test(b)&&(b=b.replace(f,function(b){return"\\u"+("0000"+b.charCodeAt(0).toString(16)).slice(-4)}));if(/^[\],:{}\s]*$/.test(b.replace(RegExp('\\\\(?:["\\\\/bfnrt]|u[0-9a-fA-F]{4})',"g"),"@").replace(RegExp('"[^"\\\\\n\r]*"|true|false|null|-?\\d+(?:\\.\\d*)?(?:[eE][+\\-]?\\d+)?',
"g"),"]").replace(RegExp("(?:^|:|,)(?:\\s*\\[)+","g"),"")))return e=eval("("+b+")"),"function"===typeof c?d({"":e},""):e;throw new SyntaxError("JSON2.parse");})})();"object"!==typeof _paqAnts&&(_paqAnts=[]);
"object"!==typeof PiwikAnts&&(PiwikAnts=function(){function b(a){return"undefined"!==typeof a}function e(a){return"function"===typeof a}function c(a){return"object"===typeof a}function f(a){return"string"===typeof a||a instanceof String}function d(){var a,b,s;for(a=0;a<arguments.length;a+=1)s=arguments[a],b=s.shift(),f(b)?V[b].apply(V,s):b.apply(V,s)}function g(a,b,s,e){if(a.addEventListener)return a.addEventListener(b,s,e),!0;if(a.attachEvent)return a.attachEvent("on"+b,s);a["on"+b]=s}function u(a,
b){var s="",c,d;for(c in oa)Object.prototype.hasOwnProperty.call(oa,c)&&(d=oa[c][a],e(d)&&(s+=d(b)));return s}function m(){var a;if(!ca)for(ca=!0,u("load"),a=0;a<va.length;a++)va[a]();return!0}function x(a,b){var s=k.createElement("script");s.type="text/javascript";s.src=a;s.readyState?s.onreadystatechange=function(){var a=this.readyState;if("loaded"===a||"complete"===a)s.onreadystatechange=null,b()}:s.onload=b;k.getElementsByTagName("head")[0].appendChild(s)}function S(){var a="";try{a=n.top.document.referrer}catch(b){if(n.parent)try{a=
n.parent.document.referrer}catch(s){a=""}}""===a&&(a=k.referrer);return a}function P(a){return(a=/^([a-z]+):/.exec(a))?a[1]:null}function p(a){var b=/^(?:(?:https?|ftp):)\/*(?:[^@]+@)?([^:/#]+)/.exec(a);return b?b[1]:a}function $(a,b){var s=RegExp("[\\?\x26#]"+b+"\x3d([^\x26#]*)").exec(a);return s?wa(s[1]):""}function w(a){var b=function(a,b){return a<<b|a>>>32-b},s=function(a){var b="",y,c;for(y=7;0<=y;y--)c=a>>>4*y&15,b+=c.toString(16);return b},c,e,d=[],f=1732584193,w=4023233417,g=2562383102,r=
271733878,z=3285377520,q,v,k,h,n,m=[];a=gb(B(a));q=a.length;for(c=0;c<q-3;c+=4)e=a.charCodeAt(c)<<24|a.charCodeAt(c+1)<<16|a.charCodeAt(c+2)<<8|a.charCodeAt(c+3),m.push(e);switch(q&3){case 0:c=2147483648;break;case 1:c=a.charCodeAt(q-1)<<24|8388608;break;case 2:c=a.charCodeAt(q-2)<<24|a.charCodeAt(q-1)<<16|32768;break;case 3:c=a.charCodeAt(q-3)<<24|a.charCodeAt(q-2)<<16|a.charCodeAt(q-1)<<8|128}for(m.push(c);14!==(m.length&15);)m.push(0);m.push(q>>>29);m.push(q<<3&4294967295);for(a=0;a<m.length;a+=
16){for(c=0;16>c;c++)d[c]=m[a+c];for(c=16;79>=c;c++)d[c]=b(d[c-3]^d[c-8]^d[c-14]^d[c-16],1);e=f;q=w;v=g;k=r;h=z;for(c=0;19>=c;c++)n=b(e,5)+(q&v|~q&k)+h+d[c]+1518500249&4294967295,h=k,k=v,v=b(q,30),q=e,e=n;for(c=20;39>=c;c++)n=b(e,5)+(q^v^k)+h+d[c]+1859775393&4294967295,h=k,k=v,v=b(q,30),q=e,e=n;for(c=40;59>=c;c++)n=b(e,5)+(q&v|q&k|v&k)+h+d[c]+2400959708&4294967295,h=k,k=v,v=b(q,30),q=e,e=n;for(c=60;79>=c;c++)n=b(e,5)+(q^v^k)+h+d[c]+3395469782&4294967295,h=k,k=v,v=b(q,30),q=e,e=n;f=f+e&4294967295;
w=w+q&4294967295;g=g+v&4294967295;r=r+k&4294967295;z=z+h&4294967295}n=s(f)+s(w)+s(g)+s(r)+s(z);return n.toLowerCase()}function z(a,b,c){if("translate.googleusercontent.com"===a)""===c&&(c=b),b=$(b,"u"),a=p(b);else if("cc.bingj.com"===a||"webcache.googleusercontent.com"===a||"74.6."===a.slice(0,5))b=k.links[0].href,a=p(b);return[a,b,c]}function q(a){var b=a.length;"."===a.charAt(--b)&&(a=a.slice(0,b));"*."===a.slice(0,2)&&(a=a.slice(1));return a}function v(a){a=a&&a.text?a.text:a;if(!f(a)){var c=k.getElementsByTagName("title");
c&&b(c[0])&&(a=c[0].text)}return a}function r(a){return a?!b(a.children)&&b(a.childNodes)||b(a.children)?a.children:[]:[]}function aa(a,c){if(a&&a.indexOf)return a.indexOf(c);if(!b(a)||null===a||!a.length)return-1;var e=a.length;if(0===e)return-1;for(var d=0;d<e;){if(a[d]===c)return d;d++}return-1}function ya(a){function c(a,b){if(n.getComputedStyle)return k.defaultView.getComputedStyle(a,null)[b];if(a.currentStyle)return a.currentStyle[b]}function e(d,f,w,q,g,r,v){var z=d.parentNode,h;a:{for(h=d.parentNode;h;){if(h===
k){h=!0;break a}h=h.parentNode}h=!1}if(!h)return!1;if(9===z.nodeType)return!0;if("0"===c(d,"opacity")||"none"===c(d,"display")||"hidden"===c(d,"visibility"))return!1;b(f)&&b(w)&&b(q)&&b(g)&&b(r)&&b(v)||(f=d.offsetTop,g=d.offsetLeft,q=f+d.offsetHeight,w=g+d.offsetWidth,r=d.offsetWidth,v=d.offsetHeight);if(a===d&&(0===v||0===r)&&"hidden"===c(d,"overflow"))return!1;if(z){if("hidden"===c(z,"overflow")||"scroll"===c(z,"overflow"))if(g+1>z.offsetWidth+z.scrollLeft||g+r-1<z.scrollLeft||f+1>z.offsetHeight+
z.scrollTop||f+v-1<z.scrollTop)return!1;d.offsetParent===z&&(g+=z.offsetLeft,f+=z.offsetTop);return e(z,f,w,q,g,r,v)}return!0}return a?e(a):!1}function Q(a,b){if(b)return b;"piwik.php"===a.slice(-9)&&(a=a.slice(0,a.length-9));return a}function H(a){var b=/index\.php\?module=Overlay&action=startOverlaySession&idSite=([0-9]+)&period=([^&]+)&date=([^&]+)$/.exec(k.referrer);if(b){if(b[1]!==String(a))return!1;n.name="Piwik_Overlay###"+b[2]+"###"+b[3]}a=n.name.split("###");return 3===a.length&&"Piwik_Overlay"===
a[0]}function A(a,b,c){var d=n.name.split("###"),e=d[1],f=d[2],w=Q(a,b);x(w+"plugins/Overlay/client/client.js?v\x3d1",function(){Piwik_Overlay_Client.initialize(w,c,e,f)})}function E(a,d){function s(l,a,b,c,d,e){if(!da){var y;b&&(y=new Date,y.setTime(y.getTime()+b));k.cookie=l+"\x3d"+B(a)+(b?";expires\x3d"+y.toGMTString():"")+";path\x3d"+(c||"/")+(d?";domain\x3d"+d:"")+(e?";secure":"")}}function r(l){return da?0:(l=RegExp("(^|;)[ ]*"+l+"\x3d([^;]*)").exec(k.cookie))?wa(l[2]):0}function m(l){var a;
return hb?(a=/#.*/,l.replace(a,"")):l}function aa(l){var a,b,c;for(a=0;a<za.length;a++){b=q(za[a].toLowerCase());if(l===b)return!0;if("."===b.slice(0,1)){if(l===b.slice(1))return!0;c=l.length-b.length;if(0<c&&l.slice(c)===b)return!0}}return!1}function x(l,a,b){b=!0;"undefined"==typeof a||a||(b=!1);a=document.createElement("script");a.type="text/javascript";a.async=b;a.src=W+(0>W.indexOf("?")?"?":"\x26")+l;a.onload=function(){};l=document.getElementsByTagName("script")[0];l.parentNode.insertBefore(a,
l)}function E(l,a,R){b(R)&&null!==R||(R=!0);try{var c=n.XMLHttpRequest?new n.XMLHttpRequest:n.ActiveXObject?new ActiveXObject("Microsoft.XMLHTTP"):null;c.open("POST",W,!0);c.onreadystatechange=function(){4!==this.readyState||200<=this.status&&300>this.status||!R?"function"===typeof a&&a():x(l,!0,a)};c.setRequestHeader("Content-Type",ib);c.send(l)}catch(d){R&&x(l,!0,a)}}function Q(l){l=(new Date).getTime()+l;if(!C||l>C)C=l}function K(l){var a=(new Date).getTime();ga&&a<ga?(a=ga-a,setTimeout(l,a),Q(a+
50),ga+=50):(!1===ga&&(ga=a+800),l())}function T(l,a,b,c){!Aa&&l&&K(function(){"POST"===jb?E(l,c):x(l,b,c);Q(a)})}function V(l,a){var b;b=Aa?!1:l&&l.length;if(b){var c='{"requests":["?'+l.join('","?')+'"]}';K(function(){E(c,null,!1);Q(a)})}}function L(l){return kb+l+"."+N+"."+lb}function ka(){if(da)return"0";if(!b(F.cookieEnabled)){var l=L("testcookie");s(l,"1");return"1"===r(l)?"1":"0"}return F.cookieEnabled?"1":"0"}function ia(){lb=Ma((X||Na)+(Y||"/")).slice(0,4)}function ja(){var l=L("cvar"),l=
r(l);return l.length&&(l=JSON2.parse(l),c(l))?l:{}}function M(){Oa=(new Date).getTime()}function eb(){var l=new Date,a=Math.round(l.getTime()/1E3),b=L("id");return(b=r(b))?(l=b.split("."),l.unshift("0"),pa.length&&(l[1]=pa),l):l=["1",pa.length?pa:Ma((F.userAgent||"")+(F.platform||"")+JSON2.stringify(Z)+l.getTime()+Math.random()).slice(0,16),a,0,a,"",""]}function xa(){var l=eb(),a=l[0],c=l[1],d=l[2],e=l[3],y=l[4],f=l[5];b(l[6])||(l[6]="");return{newVisitor:a,uuid:c,createTs:d,visitCount:e,currentVisitTs:y,
lastVisitTs:f,lastEcommerceOrderTs:l[6]}}function fb(){var l=(new Date).getTime(),a=xa().createTs;return 1E3*parseInt(a,10)+Pa-l}function La(a){if(N){var D=Math.round((new Date).getTime()/1E3);b(a)||(a=xa());a=a.uuid+"."+a.createTs+"."+a.visitCount+"."+D+"."+a.lastVisitTs+"."+a.lastEcommerceOrderTs;s(L("id"),a,fb(),Y,X)}}function la(){var a=r(L("ref"));if(a.length)try{if(a=JSON2.parse(a),c(a))return a}catch(b){}return["","",0,""]}function mb(){var a=da;da=!1;s(L("id"),"",-86400,Y,X);s(L("ses"),"",
-86400,Y,X);s(L("cvar"),"",-86400,Y,X);s(L("ref"),"",-86400,Y,X);da=a}function nb(a){if(a&&c(a)){var b=[],R;for(R in a)Object.prototype.hasOwnProperty.call(a,R)&&b.push(R);R={};b.sort();var d=b.length,e;for(e=0;e<d;e++)R[b[e]]=a[b[e]];return R}}function U(a,D,c,d){function y(a,l){var b=JSON2.stringify(a);return 2<b.length?(b=B(b),""!=b&&(0>b.lastIndexOf("5D%7D")&&b.lastIndexOf("5D%7D")+4!=b.length-1)&&(b+="5D%7D"),"\x26"+l+"\x3d"+b):""}var f,w=new Date,g=Math.round(w.getTime()/1E3),q,z,v,h,n=J,t=
L("ses"),A=L("ref"),ya=L("cvar");v=r(t);h=la();var x=Ba||ob,C,H;da&&mb();if(Aa)return"";t=xa();b(d)||(d="");var Q=k.characterSet||k.charset;Q&&"utf-8"!==Q.toLowerCase()||(Q=null);C=h[0];H=h[1];q=h[2];z=h[3];if(!v){v=Ca/1E3;if(!t.lastVisitTs||g-t.lastVisitTs>v)t.visitCount++,t.lastVisitTs=t.currentVisitTs;if(!Qa||!C.length){for(f in Da)if(Object.prototype.hasOwnProperty.call(Da,f)&&(C=$(x,Da[f]),C.length))break;for(f in Ea)if(Object.prototype.hasOwnProperty.call(Ea,f)&&(H=$(x,Ea[f]),H.length))break}v=
p(qa);h=z.length?p(z):"";!v.length||(aa(v)||Qa&&h.length&&!aa(h))||(z=qa);if(z.length||C.length)q=g,h=[C,H,q,m(z.slice(0,100))],s(A,JSON2.stringify(h),pb,Y,X)}a+="\x26idsite\x3d"+N+"\x26rec\x3d1\x26r\x3d"+String(Math.random()).slice(2,8)+"\x26h\x3d"+w.getHours()+"\x26m\x3d"+w.getMinutes()+"\x26s\x3d"+w.getSeconds()+"\x26url\x3d"+B(m(x))+(qa.length?"\x26urlref\x3d"+B(m(qa)):"")+(ma&&ma.length?"\x26uid\x3d"+B(ma):"")+"\x26_id\x3d"+t.uuid+"\x26_idts\x3d"+t.createTs+"\x26_idvc\x3d"+t.visitCount+"\x26_idn\x3d"+
t.newVisitor+(C.length?"\x26_rcn\x3d"+B(C):"")+(H.length?"\x26_rck\x3d"+B(H):"")+"\x26_refts\x3d"+q+"\x26_viewts\x3d"+t.lastVisitTs+(String(t.lastEcommerceOrderTs).length?"\x26_ects\x3d"+t.lastEcommerceOrderTs:"")+(String(z).length?"\x26_ref\x3d"+B(m(z.slice(0,100))):"")+(Q?"\x26cs\x3d"+B(Q):"")+"\x26send_image\x3d0";for(f in Z)Object.prototype.hasOwnProperty.call(Z,f)&&(a+="\x26"+f+"\x3d"+Z[f]);D?a+="\x26data\x3d"+B(JSON2.stringify(D)):ea&&(a+="\x26data\x3d"+B(JSON2.stringify(ea)));D=nb(ha);w=nb(Ra);
a+=y(D,"cvar");a+=y(w,"e_cvar");if(J){a+=y(J,"_cvar");for(f in n)Object.prototype.hasOwnProperty.call(n,f)&&(""!==J[f][0]&&""!==J[f][1]||delete J[f]);qb&&s(ya,JSON2.stringify(J),Ca,Y,X)}rb&&(Sa?a+="\x26gt_ms\x3d"+Sa:ba&&(ba.timing&&ba.timing.requestStart&&ba.timing.responseEnd)&&(a+="\x26gt_ms\x3d"+(ba.timing.responseEnd-ba.timing.requestStart)));t.lastEcommerceOrderTs=b(d)&&String(d).length?d:t.lastEcommerceOrderTs;La(t);s(L("ses"),"*",Ca,Y,X);a+=u(c);Ta.length&&(a+="\x26"+Ta);e(Ua)&&(a=Ua(a));return a}
function sb(a,D,c,d,e,y,f,s){a="idgoal\x3d"+a;var w;s=new Date;var g=[],q;String(D).length&&(a+="\x26ec_id\x3d"+B(D),w=Math.round(s.getTime()/1E3));a+="\x26revenue\x3d"+c;String(d).length&&(a+="\x26ec_st\x3d"+d);String(e).length&&(a+="\x26ec_tx\x3d"+e);String(y).length&&(a+="\x26ec_sh\x3d"+y);String(f).length&&(a+="\x26ec_dt\x3d"+f);if(I){for(q in I)Object.prototype.hasOwnProperty.call(I,q)&&(b(I[q][1])||(I[q][1]=""),b(I[q][2])||(I[q][2]=""),b(I[q][3])&&0!==String(I[q][3]).length||(I[q][3]=0),b(I[q][4])&&
0!==String(I[q][4]).length||(I[q][4]=1),g.push(I[q]));a+="\x26ec_items\x3d"+B(JSON2.stringify(g))}a=U(a,ea,"ecommerce",w);T(a,G,!1)}function Ub(a,b){var c=new Date,d=U("action_name\x3d"+B(v(a||tb)),b,"log");T(d,G,!0);Va&&(ra&&!ub)&&(ub=!0,g(k,"click",M),g(k,"mouseup",M),g(k,"mousedown",M),g(k,"mousemove",M),g(k,"mousewheel",M),g(n,"DOMMouseScroll",M),g(n,"scroll",M),g(k,"keypress",M),g(k,"keydown",M),g(k,"keyup",M),g(n,"resize",M),g(n,"focus",M),g(n,"blur",M),Oa=c.getTime(),setTimeout(function Sb(){var a;
c=new Date;Oa+ra>c.getTime()&&(Va<c.getTime()&&(a=U("ping\x3d1",b,"ping"),T(a,G,!0)),setTimeout(Sb,ra))},ra))}function Wa(a,b){var c,d="(^| )(piwik[_-]"+b;if(a)for(c=0;c<a.length;c++)d+="|"+a[c];return RegExp(d+")( |$)")}function sa(a){return W&&a&&0===String(a).indexOf(W)}function Xa(a){var D=a;for(a=D.parentNode;null!==a&&b(a)&&!h.isLinkElement(D);)D=a,a=D.parentNode;a=D;if(h.hasNodeAttribute(a,"href")&&b(a.href)&&(D=h.getAttributeValueFromNode(a,"href"),!sa(D))){var D=a.hostname||p(a.href),c=D.toLowerCase(),
D=a.href.replace(D,c);if(!/^(javascript|vbscript|jscript|mocha|livescript|ecmascript|mailto):/i.test(D)){a=a.className;c=aa(c);if(sa(D))a=0;else{var d=Wa(vb,"download"),e=Wa(wb,"link"),y=RegExp("\\.("+ta+")([?\x26#]|$)","i");a=e.test(a)?"link":d.test(a)||y.test(D)?"download":c?0:"link"}if(a)return{type:a,href:D}}}}function ua(a,b,c,d){if(a=t.buildInteractionRequestParams(a,b,c,d))return U(a,null,"contentInteraction")}function xb(a,c,d,e,y){if(b(a)){if(sa(a))return a;var f=t.toAbsoluteUrl(a),f="redirecturl\x3d"+
B(f)+"\x26",f=f+ua(c,d,e,y||a);a="\x26";0>W.indexOf("?")&&(a="?");return W+a+f}}function Ya(a,b){if(!a||!b)return!1;var c=t.findTargetNode(a);if(t.shouldIgnoreInteraction(c))return!1;c=t.findTargetNodeNoDefault(a);return!c||c&&b&&(c.contains?c.contains(b):c===b||c.compareDocumentPosition&&c.compareDocumentPosition(b)&16)?!0:!1}function yb(a,b,c){if(a){var d=t.findParentContentNode(a);if(d&&Ya(d,a)&&(a=t.buildContentBlock(d)))return!a.target&&c&&(a.target=c),t.buildInteractionRequestParams(b,a.name,
a.piece,a.target)}}function zb(a){if(!fa||!fa.length)return!1;var b,c;for(b=0;b<fa.length;b++)if((c=fa[b])&&c.name===a.name&&c.piece===a.piece&&c.target===a.target)return!0;return!1}function Za(a){if(!a)return!1;var b=t.findTargetNode(a);if(!b||t.shouldIgnoreInteraction(b))return!1;var c=Xa(b);if($a&&c&&c.type)return!1;if(h.isLinkElement(b)&&h.hasNodeAttributeWithValue(b,"href")){c=String(h.getAttributeValueFromNode(b,"href"));if(0===c.indexOf("#"))return!1;if(sa(c))return!0;if(!t.isUrlToCurrentDomain(c))return!1;
var d=t.buildContentBlock(a);if(!d)return;a=d.name;var e=d.piece,d=d.target;if(!h.hasNodeAttributeWithValue(b,t.CONTENT_TARGET_ATTR)||b.wasContentTargetAttrReplaced)b.wasContentTargetAttrReplaced=!0,d=t.toAbsoluteUrl(c),h.setAnyAttribute(b,t.CONTENT_TARGET_ATTR,d);c=xb(c,"click",a,e,d);t.setHrefAttribute(b,c);return!0}return!1}function Ab(a){return function(b){if(a){var c=t.findParentContentNode(a),d;b&&(d=b.target||b.srcElement);d||(d=a);if(Ya(c,d)){Q(G);h.isLinkElement(a)&&(h.hasNodeAttributeWithValue(a,
"href")&&h.hasNodeAttributeWithValue(a,t.CONTENT_TARGET_ATTR))&&(b=h.getAttributeValueFromNode(a,"href"),!sa(b)&&a.wasContentTargetAttrReplaced&&h.setAnyAttribute(a,t.CONTENT_TARGET_ATTR,""));b=Xa(a);if(Fa&&b&&b.type)return b.type;if(Za(c))return"href";if(c=t.buildContentBlock(c))return c=ua("click",c.name,c.piece,c.target),T(c,G,!0),c}}}}function Bb(a){if(a&&a.length){var b,c;for(b=0;b<a.length;b++)(c=t.findTargetNode(a[b]))&&!c.contentInteractionTrackingSetupDone&&(c.contentInteractionTrackingSetupDone=
!0,g(c,"click",Ab(c)))}}function Cb(a,b){if(!a||!a.length)return[];var c,d;for(c=0;c<a.length;c++)zb(a[c])?(a.splice(c,1),c--):fa.push(a[c]);if(!a||!a.length)return[];if(b&&b.length)for(c=0;c<b.length;c++)Za(b[c]);Bb(b);var e=[];for(c=0;c<a.length;c++)d=U(t.buildImpressionRequestParams(a[c].name,a[c].piece,a[c].target),void 0,"contentImpressions"),e.push(d);return e}function Ga(a){var b=t.collectContent(a);return Cb(b,a)}function ab(a){if(!a||!a.length)return[];var b;for(b=0;b<a.length;b++)t.isNodeVisible(a[b])||
(a.splice(b,1),b--);return a&&a.length?Ga(a):[]}function Db(a,b,c){a=t.buildImpressionRequestParams(a,b,c);return U(a,null,"contentImpression")}function Eb(a,b){if(a){var c=t.findParentContentNode(a);if(c=t.buildContentBlock(c))return b||(b="Unknown"),ua(b,c.name,c.piece,c.target)}}function Fb(a,c,d,e,y){if(0===String(a).length||0===String(c).length)return!1;a=U("e_c\x3d"+B(a)+"\x26e_a\x3d"+B(c)+(b(d)?"\x26e_n\x3d"+B(d):"")+(b(e)?"\x26e_v\x3d"+B(e):""),y,"event");T(a,G,!0)}function Gb(a,b,c,d,e){b=
b+"\x3d"+B(m(a));(a=yb(e,"click",a))&&(b+="\x26"+a);c=U(b,c,"link");T(c,d?0:G,!0,d)}function O(a){var b,c,d=["","webkit","ms","moz"],e;if(!Hb)for(c=0;c<d.length;c++)if(e=d[c],Object.prototype.hasOwnProperty.call(k,""!==e?e+"H"+"hidden".slice(1):"hidden")){"prerender"===k[""!==e?e+"V"+"visibilityState".slice(1):"visibilityState"]&&(b=!0);break}b?g(k,e+"visibilitychange",function Tb(){k.removeEventListener(e+"visibilitychange",Tb,!1);a()}):a()}function Ha(a){"complete"===k.readyState?a():n.addEventListener?
n.addEventListener("load",a):n.attachEvent&&n.attachEvent("onLoad",a)}function bb(a){var b=!1;(b=k.attachEvent?"complete"===k.readyState:"loading"!==k.readyState)?a():k.addEventListener?k.addEventListener("DOMContentLoaded",a):k.attachEvent&&k.attachEvent("onreadystatechange",a)}function Ib(a){var b=Xa(a);b&&b.type&&(b.href=gb(b.href),Gb(b.href,b.type,void 0,null,a))}function cb(a){var b,c;a=a||n.event;b=a.which||a.button;c=a.target||a.srcElement;"click"===a.type?c&&Ib(c):"mousedown"===a.type?1!==
b&&2!==b||!c?Ia=Ja=null:(Ia=b,Ja=c):"mouseup"===a.type&&(b===Ia&&c===Ja&&Ib(c),Ia=Ja=null)}function Jb(a,b){b?(g(a,"mouseup",cb,!1),g(a,"mousedown",cb,!1)):g(a,"click",cb,!1)}function Kb(a){if(!Fa){Fa=!0;var b,c=Wa(Lb,"ignore"),d=k.links;if(d)for(b=0;b<d.length;b++)c.test(d[b].className)||Jb(d[b],a)}}function Mb(a,b,c){function d(){e=!0}if(na)return!0;na=!0;var e=!1,y,f;Ha(function(){function s(a){setTimeout(function(){na&&(e=!1,c.trackVisibleContentImpressions(),s(a))},a)}function w(a){setTimeout(function(){na&&
(e&&(e=!1,c.trackVisibleContentImpressions()),w(a))},a)}if(a){y=["scroll","resize"];for(f=0;f<y.length;f++)k.addEventListener?k.addEventListener(y[f],d):n.attachEvent("on"+y[f],d);w(100)}b&&0<b&&(b=parseInt(b,10),s(b))})}var Ka={},db=z(k.domain,n.location.href,S()),Na=q(db[0]),ob=wa(db[1]),qa=wa(db[2]),Nb=!1,jb="GET",ib="application/x-www-form-urlencoded; charset\x3dUTF-8",W=a||"",Ob="",Ta="",N=d||"",ma="",pa="",Ba,tb=k.title,ta="7z|aac|apk|ar[cj]|as[fx]|avi|azw3|bin|csv|deb|dmg|docx?|epub|exe|flv|gif|gz|gzip|hqx|jar|jpe?g|js|mobi|mp(2|3|4|e?g)|mov(ie)?|ms[ip]|od[bfgpst]|og[gv]|pdf|phps|png|pptx?|qtm?|ra[mr]?|rpm|sea|sit|tar|t?bz2?|tgz|torrent|txt|wav|wm[av]|wpd||xlsx?|xml|z|zip",
za=[Na],Lb=[],vb=[],wb=[],G=500,Va,ra,hb,ea,Da=["pk_campaign","piwik_campaign","utm_campaign","utm_source","utm_medium"],Ea=["pk_kwd","piwik_kwd","utm_term"],kb="_pk_",X,Y,da=!1,Aa,Hb,Qa,Pa=339552E5,Ca=18E5,pb=15768E6,rb=!0,Sa=0,qb=!1,J=!1,Ua,ha={},Ra={},I={},Z={},fa=[],na=!1,ga=!1,Fa=!1,$a=!1,ub=!1,Oa,Ia,Ja,Ma=w,lb;(function(){var a,c,d={pdf:"application/pdf",qt:"video/quicktime",realp:"audio/x-pn-realaudio-plugin",wma:"application/x-mplayer2",dir:"application/x-director",fla:"application/x-shockwave-flash",
java:"application/x-java-vm",gears:"application/x-googlegears",ag:"application/x-silverlight"},y=/Mac OS X.*Safari\//.test(F.userAgent)?n.devicePixelRatio||1:1;if(!/MSIE/.test(F.userAgent)){if(F.mimeTypes&&F.mimeTypes.length)for(a in d)Object.prototype.hasOwnProperty.call(d,a)&&(c=F.mimeTypes[d[a]],Z[a]=c&&c.enabledPlugin?"1":"0");"unknown"!==typeof navigator.javaEnabled&&(b(F.javaEnabled)&&F.javaEnabled())&&(Z.java="1");e(n.GearsFactory)&&(Z.gears="1");Z.cookie=ka()}Z.res=Pb.width*y+"x"+Pb.height*
y})();ia();La();u("run",function(a,d){var e=null;if(f(a)&&!b(Ka[a])&&d){if(c(d))e=d;else if(f(d))try{eval("hookObj \x3d"+d)}catch(y){}Ka[a]=e}return e});return{hook:Ka,getHook:function(a){return Ka[a]},getQuery:function(){return h},getContent:function(){return t},buildContentImpressionRequest:Db,buildContentInteractionRequest:ua,buildContentInteractionRequestNode:Eb,buildContentInteractionTrackingRedirectUrl:xb,getContentImpressionsRequestsFromNodes:Ga,getCurrentlyVisibleContentImpressionsRequestsIfNotTrackedYet:ab,
trackCallbackOnLoad:Ha,trackCallbackOnReady:bb,buildContentImpressionsRequests:Cb,wasContentImpressionAlreadyTracked:zb,appendContentInteractionToRequestIfPossible:yb,setupInteractionsTracking:Bb,trackContentImpressionClickInteraction:Ab,internalIsNodeVisible:ya,isNodeAuthorizedToTriggerInteraction:Ya,replaceHrefIfInternalLink:Za,getConfigDownloadExtensions:function(){return ta},enableTrackOnlyVisibleContent:function(a,b){return Mb(a,b,this)},clearTrackedContentImpressions:function(){fa=[]},getTrackedContentImpressions:function(){return fa},
clearEnableTrackOnlyVisibleContent:function(){na=!1},disableLinkTracking:function(){$a=Fa=!1},getConfigVisitorCookieTimeout:function(){return Pa},getRemainingVisitorCookieTimeout:fb,getVisitorId:function(){return xa().uuid},getVisitorInfo:function(){return eb()},getAttributionInfo:function(){return la()},getAttributionCampaignName:function(){return la()[0]},getAttributionCampaignKeyword:function(){return la()[1]},getAttributionReferrerTimestamp:function(){return la()[2]},getAttributionReferrerUrl:function(){return la()[3]},
setTrackerUrl:function(a){W=a},getTrackerUrl:function(){return W},getSiteId:function(){return N},setSiteId:function(a){N=a;La()},setUserId:function(a){ma=a;pa=Ma(ma).substr(0,16)},getUserId:function(){return ma},setCustomData:function(a,b){c(a)?ea=a:(ea||(ea={}),ea[a]=b)},getCustomData:function(){return ea},setCustomRequestProcessing:function(a){Ua=a},appendToTrackingUrl:function(a){Ta=a},getRequest:function(a){return U(a)},addPlugin:function(a,b){oa[a]=b},setCustomVariable:function(a,c,d,e){b(e)||
(e="visit");b(c)&&(b(d)||(d=""),0<a&&(c=f(c)?c:String(c),d=f(d)?d:String(d),c=[c.slice(0,200),d.slice(0,200)],"visit"===e||2===e?(!1===J&&(J=ja()),J[a]=c):"page"===e||3===e?ha[a]=c:"event"===e&&(Ra[a]=c)))},getCustomVariable:function(a,c){var d;b(c)||(c="visit");if("page"===c||3===c)d=ha[a];else if("event"===c)d=Ra[a];else if("visit"===c||2===c)!1===J&&(J=ja()),d=J[a];return!b(d)||d&&""===d[0]?!1:d},deleteCustomVariable:function(a,b){this.getCustomVariable(a,b)&&this.setCustomVariable(a,"","",b)},
storeCustomVariablesInCookie:function(){qb=!0},setLinkTrackingTimer:function(a){G=a},setDownloadExtensions:function(a){ta=a},addDownloadExtensions:function(a){ta+="|"+a},setDomains:function(a){za=f(a)?[a]:a;za.push(Na)},setIgnoreClasses:function(a){Lb=f(a)?[a]:a},setRequestMethod:function(a){jb=a||"GET"},setRequestContentType:function(a){ib=a||"application/x-www-form-urlencoded; charset\x3dUTF-8"},setReferrerUrl:function(a){qa=a},setCustomUrl:function(a){var b=ob,c;P(a)?Ba=a:"/"===a.slice(0,1)?Ba=
P(b)+"://"+p(b)+a:(b=m(b),c=b.indexOf("?"),0<=c&&(b=b.slice(0,c)),c=b.lastIndexOf("/"),c!==b.length-1&&(b=b.slice(0,c+1)),Ba=b+a)},setDocumentTitle:function(a){tb=a},setAPIUrl:function(a){Ob=a},setDownloadClasses:function(a){vb=f(a)?[a]:a},setLinkClasses:function(a){wb=f(a)?[a]:a},setCampaignNameKey:function(a){Da=f(a)?[a]:a},setCampaignKeywordKey:function(a){Ea=f(a)?[a]:a},discardHashTag:function(a){hb=a},setCookieNamePrefix:function(a){kb=a;J=ja()},setCookieDomain:function(a){X=q(a);ia()},setCookiePath:function(a){Y=
a;ia()},setVisitorCookieTimeout:function(a){Pa=1E3*a},setSessionCookieTimeout:function(a){Ca=1E3*a},setReferralCookieTimeout:function(a){pb=1E3*a},setConversionAttributionFirstReferrer:function(a){Qa=a},disableCookies:function(){da=!0;Z.cookie="0"},deleteCookies:function(){mb()},setDoNotTrack:function(a){var b=F.doNotTrack||F.msDoNotTrack;(Aa=a&&("yes"===b||"1"===b))&&this.disableCookies()},addListener:function(a,b){Jb(a,b)},enableLinkTracking:function(a){$a=!0;ca?Kb(a):va.push(function(){Kb(a)})},
enableJSErrorTracking:function(){if(!Nb){Nb=!0;var a=n.onerror;n.onerror=function(b,c,d,e,y){O(function(){var a=c+":"+d;e&&(a+=":"+e);Fb("JavaScript Errors",a,b)});return a?a(b,c,d,e,y):!1}}},disablePerformanceTracking:function(){rb=!1},setGenerationTimeMs:function(a){Sa=parseInt(a,10)},setHeartBeatTimer:function(a,b){Va=(new Date).getTime()+1E3*a;ra=1E3*b},killFrame:function(){n.location!==n.top.location&&(n.top.location=n.location)},redirectFile:function(a){"file:"===n.location.protocol&&(n.location=
a)},setCountPreRendered:function(a){Hb=a},trackGoal:function(a,b,c){O(function(){var d=U("idgoal\x3d"+a+(b?"\x26revenue\x3d"+b:""),c,"goal");T(d,G,!1)})},trackLink:function(a,b,c,d){O(function(){Gb(a,b,c,d)})},trackPageView:function(a,b){fa=[];H(N)?O(function(){A(W,Ob,N)}):O(function(){Ub(a,b)})},trackAllContentImpressions:function(){H(N)||O(function(){bb(function(){var a=t.findContentNodes(),a=Ga(a);V(a,G)})})},trackVisibleContentImpressions:function(a,c){H(N)||(b(a)||(a=!0),b(c)||(c=750),Mb(a,c,
this),O(function(){Ha(function(){var a=t.findContentNodes(),a=ab(a);V(a,G)})}))},trackContentImpression:function(a,b,c){!H(N)&&a&&(b=b||"Unknown",O(function(){var d=Db(a,b,c);T(d,G,!0)}))},trackContentImpressionsWithinNode:function(a){!H(N)&&a&&O(function(){na?Ha(function(){var b=t.findContentNodesWithinNode(a),b=ab(b);V(b,G)}):bb(function(){var b=t.findContentNodesWithinNode(a),b=Ga(b);V(b,G)})})},trackContentInteraction:function(a,b,c,d){!H(N)&&(a&&b)&&(c=c||"Unknown",O(function(){var e=ua(a,b,
c,d);T(e,G,!0)}))},trackContentInteractionNode:function(a,b){!H(N)&&a&&O(function(){var c=Eb(a,b);T(c,G,!0)})},trackEvent:function(a,b,c,d,e){O(function(){Fb(a,b,c,d,e)})},trackSiteSearch:function(a,c,d){O(function(){var e=U("search\x3d"+B(a)+(c?"\x26search_cat\x3d"+B(c):"")+(b(d)?"\x26search_count\x3d"+d:""),void 0,"sitesearch");T(e,G,!0)})},setEcommerceView:function(a,c,d,e){b(d)&&d.length?d instanceof Array&&(d=JSON2.stringify(d)):d="";ha[5]=["_pkc",d];b(e)&&String(e).length&&(ha[2]=["_pkp",e]);
if(b(a)&&a.length||b(c)&&c.length)b(a)&&a.length&&(ha[3]=["_pks",a]),b(c)&&c.length||(c=""),ha[4]=["_pkn",c]},addEcommerceItem:function(a,b,c,d,e){a.length&&(I[a]=[a,b,c,d,e])},trackEcommerceOrder:function(a,c,d,e,y,f,s){String(c).length&&b(d)&&sb(a,c,d,e,y,f,s)},trackEcommerceCartUpdate:function(a){b(a)&&sb("","",a,"","","","","")}}}var C,oa={},k=document,F=navigator,Pb=screen,n=window,ba=n.performance||n.mozPerformance||n.msPerformance||n.webkitPerformance,ca=!1,va=[],B=n.encodeURIComponent,wa=
n.decodeURIComponent,gb=unescape,V,K,ia,h={htmlCollectionToArray:function(a){var b=[],c;if(!a||!a.length)return b;for(c=0;c<a.length;c++)b.push(a[c]);return b},find:function(a){if(!document.querySelectorAll||!a)return[];a=document.querySelectorAll(a);return this.htmlCollectionToArray(a)},findMultiple:function(a){if(!a||!a.length)return[];var b,c,d=[];for(b=0;b<a.length;b++)c=this.find(a[b]),d=d.concat(c);return d=this.makeNodesUnique(d)},findNodesByTagName:function(a,b){if(!a||!b||!a.getElementsByTagName)return[];
var c=a.getElementsByTagName(b);return this.htmlCollectionToArray(c)},makeNodesUnique:function(a){var b=[].concat(a);a.sort(function(a,c){if(a===c)return 0;var d=aa(b,a),e=aa(b,c);return d===e?0:d>e?-1:1});if(1>=a.length)return a;var c=0,d=0,e=[],f;for(f=a[c++];f;)f===a[c]&&(d=e.push(c)),f=a[c++]||null;for(;d--;)a.splice(e[d],1);return a},getAttributeValueFromNode:function(a,b){if(this.hasNodeAttribute(a,b)){if(a&&a.getAttribute)return a.getAttribute(b);if(a&&a.attributes&&"undefined"!==typeof a.attributes[b]){if(a.attributes[b].value)return a.attributes[b].value;
if(a.attributes[b].nodeValue)return a.attributes[b].nodeValue;var c,d=a.attributes;if(d){for(c=0;c<d.length;c++)if(d[c].nodeName===b)return d[c].nodeValue;return null}}}},hasNodeAttributeWithValue:function(a,b){return!!this.getAttributeValueFromNode(a,b)},hasNodeAttribute:function(a,b){return a&&a.hasAttribute?a.hasAttribute(b):a&&a.attributes?"undefined"!==typeof a.attributes[b]:!1},hasNodeCssClass:function(a,b){if(a&&b&&a.className){var c=a.className.split(" ");if(-1!==aa(c,b))return!0}return!1},
findNodesHavingAttribute:function(a,b,c){c||(c=[]);if(!a||!b)return c;a=r(a);if(!a||!a.length)return c;var d,e;for(d=0;d<a.length;d++)e=a[d],this.hasNodeAttribute(e,b)&&c.push(e),c=this.findNodesHavingAttribute(e,b,c);return c},findFirstNodeHavingAttribute:function(a,b){if(a&&b){if(this.hasNodeAttribute(a,b))return a;var c=this.findNodesHavingAttribute(a,b);if(c&&c.length)return c[0]}},findFirstNodeHavingAttributeWithValue:function(a,b){if(a&&b){if(this.hasNodeAttributeWithValue(a,b))return a;var c=
this.findNodesHavingAttribute(a,b);if(c&&c.length){var d;for(d=0;d<c.length;d++)if(this.getAttributeValueFromNode(c[d],b))return c[d]}}},findNodesHavingCssClass:function(a,b,c){c||(c=[]);if(!a||!b)return c;if(a.getElementsByClassName)return b=a.getElementsByClassName(b),this.htmlCollectionToArray(b);a=r(a);if(!a||!a.length)return[];var d,e;for(d=0;d<a.length;d++)e=a[d],this.hasNodeCssClass(e,b)&&c.push(e),c=this.findNodesHavingCssClass(e,b,c);return c},findFirstNodeHavingClass:function(a,b){if(a&&
b){if(this.hasNodeCssClass(a,b))return a;var c=this.findNodesHavingCssClass(a,b);if(c&&c.length)return c[0]}},isLinkElement:function(a){if(!a)return!1;a=String(a.nodeName).toLowerCase();return-1!==aa(["a","area"],a)},setAnyAttribute:function(a,b,c){a&&b&&(a.setAttribute?a.setAttribute(b,c):a[b]=c)}},t={CONTENT_ATTR:"data-track-content",CONTENT_CLASS:"piwikTrackContent",CONTENT_NAME_ATTR:"data-content-name",CONTENT_PIECE_ATTR:"data-content-piece",CONTENT_PIECE_CLASS:"piwikContentPiece",CONTENT_TARGET_ATTR:"data-content-target",
CONTENT_TARGET_CLASS:"piwikContentTarget",CONTENT_IGNOREINTERACTION_ATTR:"data-content-ignoreinteraction",CONTENT_IGNOREINTERACTION_CLASS:"piwikContentIgnoreInteraction",location:void 0,findContentNodes:function(){return h.findMultiple(["."+this.CONTENT_CLASS,"["+this.CONTENT_ATTR+"]"])},findContentNodesWithinNode:function(a){if(!a)return[];var b=h.findNodesHavingCssClass(a,this.CONTENT_CLASS),c=h.findNodesHavingAttribute(a,this.CONTENT_ATTR);if(c&&c.length){var d;for(d=0;d<c.length;d++)b.push(c[d])}h.hasNodeAttribute(a,
this.CONTENT_ATTR)?b.push(a):h.hasNodeCssClass(a,this.CONTENT_CLASS)&&b.push(a);return b=h.makeNodesUnique(b)},findParentContentNode:function(a){if(a)for(var b=0;a&&a!==k&&a.parentNode;){if(h.hasNodeAttribute(a,this.CONTENT_ATTR)||h.hasNodeCssClass(a,this.CONTENT_CLASS))return a;a=a.parentNode;if(1E3<b)break;b++}},findPieceNode:function(a){var b;(b=h.findFirstNodeHavingAttribute(a,this.CONTENT_PIECE_ATTR))||(b=h.findFirstNodeHavingClass(a,this.CONTENT_PIECE_CLASS));return b?b:a},findTargetNodeNoDefault:function(a){if(a){var b=
h.findFirstNodeHavingAttributeWithValue(a,this.CONTENT_TARGET_ATTR);if(b||(b=h.findFirstNodeHavingAttribute(a,this.CONTENT_TARGET_ATTR))||(b=h.findFirstNodeHavingClass(a,this.CONTENT_TARGET_CLASS)))return b}},findTargetNode:function(a){var b=this.findTargetNodeNoDefault(a);return b?b:a},findContentName:function(a){if(a){var b=h.findFirstNodeHavingAttributeWithValue(a,this.CONTENT_NAME_ATTR);if(b)return h.getAttributeValueFromNode(b,this.CONTENT_NAME_ATTR);if(b=this.findContentPiece(a))return this.removeDomainIfIsInLink(b);
if(h.hasNodeAttributeWithValue(a,"title"))return h.getAttributeValueFromNode(a,"title");b=this.findPieceNode(a);if(h.hasNodeAttributeWithValue(b,"title"))return h.getAttributeValueFromNode(b,"title");a=this.findTargetNode(a);if(h.hasNodeAttributeWithValue(a,"title"))return h.getAttributeValueFromNode(a,"title")}},findContentPiece:function(a){if(a){var b=h.findFirstNodeHavingAttributeWithValue(a,this.CONTENT_PIECE_ATTR);if(b)return h.getAttributeValueFromNode(b,this.CONTENT_PIECE_ATTR);a=this.findPieceNode(a);
if(a=this.findMediaUrlInNode(a))return this.toAbsoluteUrl(a)}},findContentTarget:function(a){if(a){var b=this.findTargetNode(a);if(h.hasNodeAttributeWithValue(b,this.CONTENT_TARGET_ATTR))return h.getAttributeValueFromNode(b,this.CONTENT_TARGET_ATTR);if(h.hasNodeAttributeWithValue(b,"href"))return a=h.getAttributeValueFromNode(b,"href"),this.toAbsoluteUrl(a);a=this.findPieceNode(a);if(h.hasNodeAttributeWithValue(a,"href"))return a=h.getAttributeValueFromNode(a,"href"),this.toAbsoluteUrl(a)}},isSameDomain:function(a){if(!a||
!a.indexOf)return!1;if(0===a.indexOf(this.getLocation().origin))return!0;a=a.indexOf(this.getLocation().host);return 8>=a&&0<=a?!0:!1},removeDomainIfIsInLink:function(a){a&&(a.search&&-1!==a.search(/^https?:\/\/[^/]+/)&&this.isSameDomain(a))&&((a=a.replace(/^.*\/\/[^/]+/,""))||(a="/"));return a},findMediaUrlInNode:function(a){if(a){var b=a.nodeName.toLowerCase();if(-1!==aa(["img","embed","video","audio"],b)&&h.findFirstNodeHavingAttributeWithValue(a,"src"))return a=h.findFirstNodeHavingAttributeWithValue(a,
"src"),h.getAttributeValueFromNode(a,"src");if("object"===b&&h.hasNodeAttributeWithValue(a,"data"))return h.getAttributeValueFromNode(a,"data");if("object"===b){if((b=h.findNodesByTagName(a,"param"))&&b.length){var c;for(c=0;c<b.length;c++)if("movie"===h.getAttributeValueFromNode(b[c],"name")&&h.hasNodeAttributeWithValue(b[c],"value"))return h.getAttributeValueFromNode(b[c],"value")}if((a=h.findNodesByTagName(a,"embed"))&&a.length)return this.findMediaUrlInNode(a[0])}}},trim:function(a){return a&&
String(a)===a?a.replace(/^\s+|\s+$/g,""):a},isOrWasNodeInViewport:function(a){if(!a||!a.getBoundingClientRect||1!==a.nodeType)return!0;var b=a.getBoundingClientRect(),c=k.documentElement||{},d=0>b.top;d&&a.offsetTop&&(d=0<a.offsetTop+b.height);a=c.clientWidth;n.innerWidth&&a>n.innerWidth&&(a=n.innerWidth);c=c.clientHeight;n.innerHeight&&c>n.innerHeight&&(c=n.innerHeight);return(0<b.bottom||d)&&0<b.right&&b.left<a&&(b.top<c||d)},isNodeVisible:function(a){var b=ya(a);a=this.isOrWasNodeInViewport(a);
return b&&a},buildInteractionRequestParams:function(a,b,c,d){var e="";a&&(e+="c_i\x3d"+B(a));b&&(e&&(e+="\x26"),e+="c_n\x3d"+B(b));c&&(e&&(e+="\x26"),e+="c_p\x3d"+B(c));d&&(e&&(e+="\x26"),e+="c_t\x3d"+B(d));return e},buildImpressionRequestParams:function(a,b,c){a="c_n\x3d"+B(a)+"\x26c_p\x3d"+B(b);c&&(a+="\x26c_t\x3d"+B(c));return a},buildContentBlock:function(a){if(a){var b=this.findContentName(a),c=this.findContentPiece(a);a=this.findContentTarget(a);b=this.trim(b);c=this.trim(c);a=this.trim(a);
return{name:b||"Unknown",piece:c||"Unknown",target:a||""}}},collectContent:function(a){if(!a||!a.length)return[];var c=[],d,e;for(d=0;d<a.length;d++)e=this.buildContentBlock(a[d]),b(e)&&c.push(e);return c},setLocation:function(a){this.location=a},getLocation:function(){var a=this.location||n.location;a.origin||(a.origin=a.protocol+"//"+a.hostname+(a.port?":"+a.port:""));return a},toAbsoluteUrl:function(a){return a&&String(a)===a||""===a?""===a?this.getLocation().href:-1!==a.search(/^\/\//)?this.getLocation().protocol+
a:-1!==a.search(/:\/\//)?a:0===a.indexOf("#")||0===a.indexOf("?")?this.getLocation().origin+this.getLocation().pathname+a:0===a.search("^[a-zA-Z]{2,11}:")?a:-1!==a.search(/^\//)?this.getLocation().origin+a:this.getLocation().origin+this.getLocation().pathname.match(/(.*\/)/)[0]+a:a},isUrlToCurrentDomain:function(a){a=this.toAbsoluteUrl(a);if(!a)return!1;var b=this.getLocation().origin;return b===a?!0:0===String(a).indexOf(b)?":"===String(a).substr(b.length,1)?!1:!0:!1},setHrefAttribute:function(a,
b){a&&b&&h.setAnyAttribute(a,"href",b)},shouldIgnoreInteraction:function(a){var b=h.hasNodeAttribute(a,this.CONTENT_IGNOREINTERACTION_ATTR);a=h.hasNodeCssClass(a,this.CONTENT_IGNOREINTERACTION_CLASS);return b||a}};g(n,"beforeunload",function(){var a;u("unload");if(C){do a=new Date;while(a.getTimeAlias()<C)}},!1);(function(){var a;k.addEventListener?g(k,"DOMContentLoaded",function s(){k.removeEventListener("DOMContentLoaded",s,!1);m()}):k.attachEvent&&(k.attachEvent("onreadystatechange",function Qb(){"complete"===
k.readyState&&(k.detachEvent("onreadystatechange",Qb),m())}),k.documentElement.doScroll&&n===n.top&&function Rb(){if(!ca){try{k.documentElement.doScroll("left")}catch(a){setTimeout(Rb,0);return}m()}}());/WebKit/.test(F.userAgent)&&(a=setInterval(function(){if(ca||/loaded|complete/.test(k.readyState))clearInterval(a),m()},10));g(n,"load",m,!1)})();Date.prototype.getTimeAlias=Date.prototype.getTime;V=new E;var ja={setTrackerUrl:1,setAPIUrl:1,setUserId:1,setSiteId:1,disableCookies:1,enableLinkTracking:1},
ka;for(K=0;K<_paqAnts.length;K++)ka=_paqAnts[K][0],ja[ka]&&(d(_paqAnts[K]),delete _paqAnts[K],1<ja[ka]&&void 0!==console&&(console&&console.error)&&console.error("The method "+ka+' is registered more than once in "_paq" variable. Only the last call has an effect. Please have a look at the multiple Piwik trackers documentation: http://developer.piwik.org/guides/tracking-javascript-guide#multiple-piwik-trackers'),ja[ka]++);for(K=0;K<_paqAnts.length;K++)_paqAnts[K]&&d(_paqAnts[K]);_paqAnts=new function(){return{push:d}};
ia={addPlugin:function(a,b){oa[a]=b},getTracker:function(a,c){b(c)||(c=this.getAsyncTracker().getSiteId());b(a)||(a=this.getAsyncTracker().getTrackerUrl());return new E(a,c)},getAsyncTracker:function(){return V}};"function"===typeof define&&define.amd&&define("piwik",[],function(){return ia});return ia}());window&&window.piwikAsyncInit&&window.piwikAsyncInit();(function(){"undefined"===typeof AnalyticsTracker&&(AnalyticsTracker=PiwikAnts)})();
"function"!==typeof piwik_log&&(piwik_log=function(b,e,c,f){function d(b){try{return eval("piwik_"+b)}catch(c){}}var g=PiwikAnts.getTracker(c,e);g.setDocumentTitle(b);g.setCustomData(f);(b=d("tracker_pause"))&&g.setLinkTrackingTimer(b);(b=d("download_extensions"))&&g.setDownloadExtensions(b);(b=d("hosts_alias"))&&g.setDomains(b);(b=d("ignore_classes"))&&g.setIgnoreClasses(b);g.trackPageView();d("install_tracker")&&(piwik_track=function(b,c,d,e){g.setSiteId(c);g.setTrackerUrl(d);g.trackLink(b,e)},
g.enableLinkTracking())});function ants_isIE(){var b=navigator.userAgent.toLowerCase();return-1!=b.indexOf("msie")?parseInt(b.split("msie")[1]):!1}if(9==ants_isIE())try{_antsLoadScript("//st-a.anthill.vn/v2/ie9.js")}catch(ex){}function b64ToUint6(b){return 64<b&&91>b?b-65:96<b&&123>b?b-71:47<b&&58>b?b+4:43===b?62:47===b?63:0}
function base64DecToArr(b,e){try{for(var c=b.replace(/[^A-Za-z0-9\+\/]/g,""),f=c.length,d=e?Math.ceil((3*f+1>>2)/e)*e:3*f+1>>2,g=new Uint8Array(d),u,m,x=0,S=0,P=0;P<f;P++)if(m=P&3,x|=b64ToUint6(c.charCodeAt(P))<<6*(3-m),3===m||1===f-P){for(u=0;3>u&&S<d;u++,S++)g[S]=x>>>(16>>>u&24)&255;x=0}return g}catch(p){return""}}function uint6ToB64(b){return 26>b?b+65:52>b?b+71:62>b?b-4:62===b?43:63===b?47:65}
function base64EncArr(b){for(var e=2,c="",f=b.length,d=0,g=0;g<f;g++)if(e=g%3,0<g&&0===4*g/3%76&&(c+="\r\n"),d|=b[g]<<(16>>>e&24),2===e||1===b.length-g)c+=String.fromCharCode(uint6ToB64(d>>>18&63),uint6ToB64(d>>>12&63),uint6ToB64(d>>>6&63),uint6ToB64(d&63)),d=0;return c.substr(0,c.length-2+e)+(2===e?"":1===e?"\x3d":"\x3d\x3d")}
function UTF8ArrToStr(b){for(var e="",c,f=b.length,d=0;d<f;d++)c=b[d],e+=String.fromCharCode(251<c&&254>c&&d+5<f?1073741824*(c-252)+(b[++d]-128<<24)+(b[++d]-128<<18)+(b[++d]-128<<12)+(b[++d]-128<<6)+b[++d]-128:247<c&&252>c&&d+4<f?(c-248<<24)+(b[++d]-128<<18)+(b[++d]-128<<12)+(b[++d]-128<<6)+b[++d]-128:239<c&&248>c&&d+3<f?(c-240<<18)+(b[++d]-128<<12)+(b[++d]-128<<6)+b[++d]-128:223<c&&240>c&&d+2<f?(c-224<<12)+(b[++d]-128<<6)+b[++d]-128:191<c&&224>c&&d+1<f?(c-192<<6)+b[++d]-128:c);return e}
function strToUTF8Arr(b){var e,c;e=b.length;for(var f=0,d=0;d<e;d++)c=b.charCodeAt(d),f+=128>c?1:2048>c?2:65536>c?3:2097152>c?4:67108864>c?5:6;e=new Uint8Array(f);for(var g=d=0;d<f;g++)c=b.charCodeAt(g),128>c?e[d++]=c:(2048>c?e[d++]=192+(c>>>6):(65536>c?e[d++]=224+(c>>>12):(2097152>c?e[d++]=240+(c>>>18):(67108864>c?e[d++]=248+(c>>>24):(e[d++]=252+(c>>>30),e[d++]=128+(c>>>24&63)),e[d++]=128+(c>>>18&63)),e[d++]=128+(c>>>12&63)),e[d++]=128+(c>>>6&63)),e[d++]=128+(c&63));return e}
function ants_encryptBase64(b){if(9==ants_isIE())return b;b=strToUTF8Arr(b);return base64EncArr(b)}function ants_decryptBase64(b){if(9==ants_isIE())return b;b=base64DecToArr(b);return UTF8ArrToStr(b)};var LOG_TRACKING_URL="//a.props.id",STATIC_FILE_URL="//st-a.props.id",_iants=_iants||[],aiFunction=aiFunction||{};window.aiFunction.randomString=function(b,e){e=e||"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz";for(var c="",f=0;f<b;f++)var d=Math.floor(Math.random()*e.length),c=c+e.substring(d,d+1);return c};
window.aiFunction.setCookie=function(b,e,c,f,d,g){var u;void 0!=c&&(u=new Date,u.setTime(u.getTime()+c));var m=e+"";isNaN(e)&&(m=window.encodeURIComponent(e));b=b+"\x3d"+m+(c?";expires\x3d"+u.toGMTString():"")+";path\x3d"+(f||"/")+(d?";domain\x3d"+d:"")+(g?";secure":"");document.cookie=b};window.aiFunction.getCookie=function(b){return(cookieMatch=RegExp("(^|;)[ ]*"+b+"\x3d([^;]*)").exec(document.cookie))?window.decodeURIComponent(cookieMatch[2]):0};
window.aiFunction.getURLParameter=function(b){for(var e=window.location.search.substring(1).split("\x26"),c=0;c<e.length;c++){var f=e[c].split("\x3d");if(f[0]==b)return f[1]}try{var d=window.location.href;if(0<d.indexOf("?utm"))for(e=d.substring(d.indexOf("?utm")+1).split("\x26"),c=0;c<e.length;c++)if(f=e[c].split("\x3d"),f[0]==b)return f[1]}catch(g){}return""};
window.aiFunction.getReferrer=function(){var b="";try{b=window.top.document.referrer}catch(e){if(window.parent)try{b=window.parent.document.referrer}catch(c){b=""}}""===b&&(b=document.referrer);return b};window.aiFunction.getHostName=function(b){var e=/^(?:(?:https?|ftp):)\/*(?:[^@]+@)?([^:/#]+)/.exec(b);return e?e[1]:b};window.aiFunction.checkHomePage=function(){var b=window.location.hostname,e=window.location.href,c="http://"+b+"/";0<=e.indexOf("https://")&&(c="https://"+b+"/");return c==e?1:0};
window.aiFunction.getReferrerDomain=function(b){b="";var e=window.aiFunction.getReferrer();void 0!=e&&(""!=e&&0<e.length)&&(e=window.aiFunction.getHostName(e),void 0!=e&&""!=e&&(b=e.replace("www.","")));return b};_ants_ecommerceItems=[];var ai_sent_sites;if("undefined"==typeof ai_sent_sites||null==ai_sent_sites)ai_sent_sites=[];var ai_sent_counter=0;
function checkSendLogProfile(b,e){if(e||0>=b.socialType)return!0;var c=!0;try{var f=_ea_get_tup(b.socialType);f==b.socialId+"-"+b.socialType&&""!=f&&(c=!1)}catch(d){}return c}
function _antsGetDefaultCookieDomain(){for(var b="net com edu org gov biz info".split(" "),e=0,c=b.length;e<c;++e)b.push(b[e]+"\\.vn");b.push("vn");b.push("us");b.push("id");var b=RegExp("(\\.?[^.]+\\.("+b.join("|")+")$)"),b=document.domain.match(b),f;null!==b?f=b[1]:(b=document.domain.match(/(\.?[^.]+\.?[^.]+$)/),null!==b&&(f=b[1]));"."==f[0]&&(f=f.substr(1));return f}
function iantsGetPageview(){if(null!=("undefined"!==typeof window&&null!==window?window._antspv:void 0))return"undefined"!==typeof window&&null!==window?window._antspv:void 0;"undefined"!==typeof window&&null!==window&&(window._antspv=(new Date).getTime());return"undefined"!==typeof window&&null!==window?window._antspv:void 0}
var _ea_get_utm=function(){var b={source:"",medium:"",campaign:"",content:"",term:"",type:"",checksum:""};try{var e=!0,c=window.aiFunction.getCookie("_ants_utm_v2");if(void 0==c||""==c)c=window.aiFunction.getCookie("_ants_utm"),e=!1;if(void 0!=c&&""!=c){var f=ants_decryptBase64(c);if(void 0!=f&&""!=f){var b=JSON2.parse(f),d=_ea_utm_checksum(b);if(e&&d==b.checksum)return b}}if("undefined"!==typeof Storage)try{if(c=window.localStorage._ants_utm_v2,void 0!=c&&""!=c){f=ants_decryptBase64(c);if(void 0!=
f&&""!=f&&(b=JSON2.parse(c),d=_ea_utm_checksum(b),e&&d!=b.checksum))return b={source:"",medium:"",campaign:"",content:"",term:"",type:"",checksum:""};var g=b.time+15552E6;if((new Date).getTime()>g)window.localStorage._ants_utm_v2="";else return window.aiFunction.setCookie("_ants_utm_v2",c,15552E6,"/","",0),b}}catch(u){}}catch(m){}return b},_ea_save_goals=function(b,e){try{if(void 0!=b&&""!=b&&"visit_page"==e){var c={checksum:b+"-"+e+"_"+window.location.href,time:(new Date).getTime()},f=JSON2.stringify(c);
key="_ants_gc_"+b;window.aiFunction.setCookie(key,f,3E5,"/","",0);"undefined"!==typeof Storage&&key&&localStorage.setItem(key,f)}}catch(d){}},_ea_get_goals_checksum=function(b,e){var c="";try{if(0>=b||"visit_page"==e)return c;key="_ants_gc_"+b;var f="",d=window.aiFunction.getCookie(key);if(void 0!=d&&""!=d)f=JSON2.parse(d);else if("undefined"!==typeof Storage)try{if(d=localStorage.getItem(key),void 0!=d&&""!=d){var f=JSON2.parse(d),g=f.time+3E5;(new Date).getTime()>g&&(localStorage.setItem(key,""),
f="")}}catch(u){}""!=f&&(c=f.checksum)}catch(m){}return c};
function AdxAnalytics(){var b=document,e=window,c=e.encodeURIComponent,f=e.decodeURIComponent,d=LOG_TRACKING_URL;this.setCookie=function(d,e,f,g,r,m){var p;f&&(p=new Date,p.setTime(p.getTime()+f));b.cookie=d+"\x3d"+c(e)+(f?";expires\x3d"+p.toGMTString():"")+";path\x3d"+(g||"/")+(r?";domain\x3d"+r:"")+(m?";secure":"")};this.getCookie=function(c){return(cookieMatch=RegExp("(^|;)[ ]*"+c+"\x3d([^;]*)").exec(b.cookie))?f(cookieMatch[2]):0};var g=new Date,u=new Date,m,x=0,S,P=this.getCookie("au_aid")||
0,p=0,$="";this.logData=function(b){try{if("undefined"!=typeof ai_sent_sites&&-1<ai_sent_sites.indexOf(b))return!1;S=this.getAntsConfig("setCookieDomain");""===S&&(S=_antsGetDefaultCookieDomain());_paqAnts.push(["setDocumentTitle",document.title]);_paqAnts.push(["setCookieDomain","*."+S]);_paqAnts.push(["setTrackerUrl",d+"/get"]);_paqAnts.push(["setSiteId",b]);var c=iantsGetPageview(),e,f,g,m,p,x;f=this.getCookie("an_session");e=this.getCookie("au_aid");x=this.getCookie("dgs");if("undefined"!==typeof Storage)try{0===
f&&(f=window.localStorage.an_session);if(void 0==e||""==e||0===e)e=window.localStorage.au_aid;g=window.localStorage.pv;m=window.localStorage.t1;p=window.localStorage.t2;null===m&&(m=0);null===p&&(p=0)}catch(H){}_paqAnts.push(["setCustomVariable","2","au_aid_bk",e,"page"]);_paqAnts.push(["setCustomVariable","3","an_session",f,"page"]);_paqAnts.push(["setCustomVariable","4","pv",g,"page"]);_paqAnts.push(["setCustomVariable","8","t1",m,"page"]);_paqAnts.push(["setCustomVariable","9","t2",p,"page"]);
_paqAnts.push(["setCustomVariable","10","time_diff",p-m,"page"]);_paqAnts.push(["setCustomVariable","11","dgs",x,"page"]);_paqAnts.push(["setCustomVariable","12","antspv",c,"page"]);var A=_ea_get_utm();void 0!=A.source&&""!=A.source&&_paqAnts.push(["setCustomVariable","13","utm_source",A.source,"page"]);void 0!=A.campaign&&""!=A.campaign&&_paqAnts.push(["setCustomVariable","14","utm_campaign",A.campaign,"page"]);void 0!=A.medium&&""!=A.medium&&_paqAnts.push(["setCustomVariable","15","utm_medium",
A.medium,"page"]);void 0!=A.content&&""!=A.content&&_paqAnts.push(["setCustomVariable","16","utm_content",A.content,"page"]);void 0!=A.term&&""!=A.term&&_paqAnts.push(["setCustomVariable","17","utm_term",A.term,"page"]);void 0!=A.term&&""!=A.term&&_paqAnts.push(["setCustomVariable","18","utm_type",A.type,"page"]);var E=window.aiFunction.checkHomePage();_paqAnts.push(["setCustomVariable","19","home",E,"page"]);_paqAnts.push(["setCustomVariable","5","des","","page"]);var C=this.getMeta("adx:keywords");
try{if(!1==C||""==C)0<window.location.href.indexOf("q\x3d")?C=window.aiFunction.getURLParameter("q"):0<window.location.href.indexOf("search\x3d")?C=window.aiFunction.getURLParameter("search"):0<window.location.href.indexOf("query\x3d")&&(C=window.aiFunction.getURLParameter("query"));if(!1==C||void 0==C||""==C)C=this.getMeta("keywords")}catch(P){}null!=C&&""!=C&&(C=C.substring(0,100),_paqAnts.push(["setCustomVariable","6","keywords",C,"page"]));var k=this.getCookie("au_aid");void 0==k&&(k=this.getCookie("an_aid"));
if(void 0==k||""==k||"0"==k||0===k||0>=parseInt(k))k=e;_paqAnts.push(["setCustomVariable","7","au_aid",k,"page"]);var F=this.getMeta("adx:sections");!1!=F&&_paqAnts.push(["setCustomVariable","50","sections",F,"page"]);var $=this.getMeta("adx:objects");!1!=$&&_paqAnts.push(["setCustomVariable","51","objects",$,"page"]);var n=this.getMeta("adx:authors");!1!=n&&_paqAnts.push(["setCustomVariable","52","authors",n,"page"]);var ba=this.getMeta("adx:users");!1!=ba&&_paqAnts.push(["setCustomVariable","53",
"users",ba,"page"]);var ca=this.getMeta("adx:cuid");!1!=ca&&_paqAnts.push(["setCustomVariable","54","cuid",ca,"page"]);PiwikAnts.getAsyncTracker().trackPageView();"undefined"!=typeof ai_sent_sites&&ai_sent_sites.push(b);if("undefined"!==typeof Storage)try{window.localStorage.t1=u.getTime()}catch(va){}}catch(B){}};this.getAntsConfig=function(b){if("undefined"===typeof _iants)return"";for(i=0;i<_iants.length;i++)if(_iants[i][0]===b)return _iants[i][1];return""};this.incrCountTimeTrack=function(b){x+=
b};this.getMydomain=function(){return S};this.getCountTimeTrack=function(){return x};this.getTrackingBaseUrl=function(){return d};this.getStartTime=function(){return u};this.getPageviewId=function(){return m};this.setPageviewId=function(b){m=b};this.setVisitorId=function(b){P=b};this.getVisitorId=function(){return P};this.setGlobalId=function(b){p=b};this.getGlobalId=function(){return p};this.setClientIP=function(b){$=b};this.getClientIP=function(){return $};this.setTimeToSendLog=function(){g=new Date};
this.getTimeToSendLog=function(){return g};this.loadScript=function(b,c){var d=document.getElementsByTagName("head")[0],e=document.createElement("script");e.type="text/javascript";e.src=b;e.async=!0;e.onreadystatechange=c;e.onload=c;d.appendChild(e)};this.getMeta=function(b){var c=document.getElementsByTagName("meta");if(0<c.length)for(var d=0;d<c.length;d++)if(null!=c[d].getAttribute("name")&&c[d].getAttribute("name").toLowerCase()==b.toLowerCase())return c[d].getAttribute("content");return!1};this.trackingPageview=
function(){try{var b=adx_analytic.getTimeToSendLog().getTime()+3E3;(new Date).getTime()<b||30<ai_sent_counter?adx_analytic.setTimeToSendLog():(adx_analytic.setTimeToSendLog(),ai_sent_counter++,ai_sent_sites=[],adx_analytic.logData(window._siteId,1))}catch(c){}};this.trackingGoalVisit=function(b,c,e){var f=adx_analytic.getPageviewId();"undefined"===typeof f&&"undefined"!==typeof pv_id&&(f=pv_id);if("undefined"!==typeof b&&"undefined"!==typeof f&&"visit_page"===e&&adx_analytic.currGoal!==b+":"+f){var g=
_ea_get_utm(),g={goal_type:e?e:"visit_page",pv_id:f,source:g.source,campaign:g.campaign,medium:g.medium,content:g.content,term:g.term};_ea_get_goals_checksum(b,e)!=b+"-"+e+"_"+window.location.href&&(_paqAnts.push(["setTrackerUrl",d+"/goal"]),_paqAnts.push(["trackGoal",b,c?c:1,g]),adx_analytic.currGoal=b+":"+f,_ea_save_goals(b,e))}};this.trackingGoal=function(b,c,e){var f=adx_analytic.getPageviewId();"undefined"===typeof f&&"undefined"!==typeof pv_id&&(f=pv_id);if("undefined"!==typeof b&&"undefined"!==
typeof f&&"visit_page"!==e&&adx_analytic.currGoal!==b+":"+f){var g=_ea_get_utm();e={goal_type:e?e:"event",pv_id:f,source:g.source,campaign:g.campaign,medium:g.medium,content:g.content,term:g.term};_paqAnts.push(["setTrackerUrl",d+"/goal"]);_paqAnts.push(["trackGoal",b,c?c:1,e]);adx_analytic.currGoal=b+":"+f}};this.trackingFormVisit=function(b,c){var e=adx_analytic.getPageviewId();"undefined"===typeof e&&"undefined"!==typeof pv_id&&(e=pv_id);if("undefined"!==typeof b&&"undefined"!==typeof e&&"visit_page"===
c&&""!=b){var f=void 0!=b.description?b.description:"";"undefined"==f&&(f="");f={name:void 0!=b.name?b.name:"",phone:void 0!=b.phone?b.phone:"",email:void 0!=b.email?b.email:"",gender:void 0!=b.gender?b.gender:"",birthday:void 0!=b.birthday?b.birthday:"",socialId:void 0!=b.socialId?b.socialId:0,socialType:void 0!=b.socialType?b.socialType:0,address:void 0!=b.address?b.address:"",description:f,others:void 0!=b.others?b.others:"",app:b.app};""!=f.name&&(f=ants_encryptBase64(JSON2.stringify(f)),b={us_info:f,
pv_id:e,encrypt:"true"},_paqAnts.push(["setTrackerUrl",d+"/goal"]),_paqAnts.push(["trackGoal","uptrack",1,b]))}};this.trackingEvent=function(b,c,e,f,g){var m=adx_analytic.getPageviewId();"undefined"===typeof m&&"undefined"!==typeof pv_id&&(m=pv_id);if("undefined"===typeof m){if("undefined"!==typeof g&&g)var p=0,x=setInterval(function(){p++;if("undefined"!=typeof adx_analytic.getPageviewId()||20<=p)adx_analytic.trackingEvent(b,c,e,f,!1),clearInterval(x)},200)}else if("tup"===b&&(g=void 0!=c.description?
c.description:"","undefined"==g&&(g=""),g={name:void 0!=c.name?c.name:"",phone:void 0!=c.phone?c.phone:"",email:void 0!=c.email?c.email:"",gender:void 0!=c.gender?c.gender:"",birthday:void 0!=c.birthday?c.birthday:"",socialId:void 0!=c.socialId?c.socialId:0,socialType:void 0!=c.socialType?c.socialType:0,address:void 0!=c.address?c.address:"",description:g,others:void 0!=c.others?c.others:"",source:void 0!=c.source?c.source:"direct",site:window._siteId,app:c.app},checkSendLogProfile(g,e)&&""!=g.name)){_ea_save_tup(g.socialId,
g.socialType);g=ants_encryptBase64(JSON2.stringify(g));var u=0;"undefined"!==typeof f&&(u=f);0!=u&&void 0!=u||!e||(u=1);c={us_info:g,pv_id:m,encrypt:"true",register_completed:e,goal_id:u,version:2};_paqAnts.push(["setTrackerUrl",d+"/goal"]);_paqAnts.push(["trackGoal","uptrack",1,c])}};this.trackingEcommerce=function(b,c,e,f,g,m,p,u){var x=adx_analytic.getPageviewId();if("undefined"!==typeof b&&"undefined"!==typeof x){if(0<_ants_ecommerceItems.length)for(var A=0;A<_ants_ecommerceItems.length;A++){var E=
_ants_ecommerceItems[A];_paqAnts.push(["addEcommerceItem",void 0!=E.id?E.id:"",void 0!=E.name?E.name:"",void 0!=E.category?E.category:"",void 0!=E.price?E.price:"",void 0!=E.quantity?E.quantity:1])}adx_analytic.currEcommerce!==c+":"+x&&(e=void 0!=e?e:0,f=void 0!=f?f:0,g=void 0!=g?g:0,m=void 0!=m?m:0,p=void 0!=p?p:0,u=void 0!=u?u:"",A=_ea_get_utm(),u={goal_type:"event",pv_id:x,source:A.source,campaign:A.campaign,medium:A.medium,content:A.content,term:A.term,others:u},_paqAnts.push(["setTrackerUrl",
d+"/ecommerce"]),_paqAnts.push(["setCustomData",u]),_paqAnts.push(["trackEcommerceOrder",b,c,e,f,g,m,p]),adx_analytic.currEcommerce=c+":"+x)}};this.trackingEventBasic=function(b,c,e,f,g,m){var p=adx_analytic.getPageviewId();"undefined"===typeof p&&"undefined"!==typeof pv_id&&(p=pv_id);"undefined"===typeof p||("undefined"===typeof b||""==b||1>=b.length)||(30<b.length&&(b=b.substring(0,30)),"undefined"===typeof c||(""==c||1>=c.length)||(30<c.length&&(c=c.substring(0,30)),"undefined"===typeof e||(""==
e||1>=e.length)||(30<e.length&&(e=e.substring(0,30)),"undefined"===typeof f||0>parseFloat(f)||adx_analytic.currEvent===c+":"+p&&!m||(g={pv_id:p,fieldsObject:g},_paqAnts.push(["setTrackerUrl",d+"/event"]),_paqAnts.push(["trackEvent",b,c,e,f,g]),adx_analytic.currEvent=c+":"+p))))};this.gt=function(b){"undefined"!=typeof ants_callbackData&&ants_callbackData(b,"gt")};this.pt=function(b){"undefined"!=typeof ants_callbackData&&ants_callbackData(b,"pt")};this.evt=function(b){"undefined"!=typeof ants_callbackData&&
ants_callbackData(b,"evt")}}window.onbeforeunload=function(b){try{var e=new Date-adx_analytic.getStartTime();"undefined"!==typeof Storage&&(window.localStorage.pv=window.localStorage.pv.replace(":0",":"+e))}catch(c){}};
var an_session,pv_id,callback_ea=function(b){var e=b.vid,c=b.au_gt,f=b.pvId,d=b.dgs,g=b.services;ants_pvId=b.pvId;an_session=b.an_session;pv_id=b.pvId;adx_analytic.setPageviewId(f);adx_analytic.setVisitorId(e);adx_analytic.setGlobalId(b.globalId);try{void 0!=b.networks&&adx_analytic.setClientIP(b.networks.client_ip)}catch(u){}var f=new Date,m="."+adx_analytic.getMydomain();window.aiFunction.setCookie("an_session",an_session,63072E6,"/",m,0);0===window.aiFunction.getCookie("au_aid")&&window.aiFunction.setCookie("au_aid",
e,63072E6,"/",m,0);"undefined"!==typeof d&&""!==d&&window.aiFunction.setCookie("dgs",d,63072E6,"/",m,0);d=window.aiFunction.getCookie("au_gt");"undefined"!==typeof d&&0!==d&&""!==d||window.aiFunction.setCookie("au_gt",c,63072E6,"/",m,0);"undefined"!==typeof g&&window.aiFunction.setCookie("_ants_services",JSON.stringify(g),63072E6,"/",m,0);"undefined"!==typeof Storage&&(b.vid&&(window.localStorage.au_aid=e),b.pvId&&(window.localStorage.pv=b.pvId+":0"),b.eatv&&(window.localStorage.eatv=b.eatv),b.an_session&&
(window.localStorage.an_session=b.an_session),b.au_gt&&""!=b.au_gt&&(window.localStorage.au_gt=b.au_gt),window.localStorage.t2=f.getTime());adx_analytic.trackingGoalVisit(window._ants_goal_id,window._ants_goal_revenue,window._ants_goal_type);adx_analytic.trackingFormVisit(window._ants_form_data,window._ants_form_type)},adx_analytic=new AdxAnalytics,_ea_loader_function=function(){try{"512041970"===window._siteId?"undefined"!=typeof FLAG_SEND_LOG&&FLAG_SEND_LOG||(adx_analytic.logData(window._siteId,
1),FLAG_SEND_LOG=!0):adx_analytic.logData(window._siteId,1)}catch(b){}};_ea_loader_function();
var _antsLoadScript=function(b){var e=document.createElement("script");e.type="text/javascript";e.async=!0;e.src=b;b=document.getElementsByTagName("script")[0];b.parentNode.insertBefore(e,b)},_antsLoadServices=function(){try{var b=window.aiFunction.getCookie("_ants_services");if(void 0!=b&&""!=b){var e=JSON.parse(b),c=b=-1,f=-1;void 0!=e&&(b=e.indexOf("dfp"),c=e.indexOf("wap"),f=e.indexOf("cuid"));(0<=b||0<=c||0<=f)&&_antsLoadScript(STATIC_FILE_URL+"/ais.js")}}catch(d){}};_antsLoadServices();
var _ea_trackfb_detail=function(){try{_antsLoadScript(STATIC_FILE_URL+"/ai.js")}catch(b){}},_ea_trackfb=function(){"515584286"===window._siteId?"undefined"!=typeof FLAG_FB&&FLAG_FB||(_ea_trackfb_detail(),FLAG_FB=!0):_ea_trackfb_detail()};_ea_trackfb();
var _ea_utm_checksum=function(b){try{return ants_encryptBase64(b.source+"-"+b.medium+"-"+b.campaign+"-"+b.time)}catch(e){}return""},_ea_save_utm=function(){try{var b="",e=!1,c=window.location.href;if(0<c.indexOf("utm_")){var f={source:window.aiFunction.getURLParameter("utm_source"),medium:window.aiFunction.getURLParameter("utm_medium"),campaign:window.aiFunction.getURLParameter("utm_campaign"),content:window.aiFunction.getURLParameter("utm_content"),term:window.aiFunction.getURLParameter("utm_term"),
type:"direct",time:(new Date).getTime(),checksum:""};f.checksum=_ea_utm_checksum(f);b=JSON2.stringify(f);e=!0}else if(0<c.indexOf("code_chanel"))f={source:window.aiFunction.getURLParameter("code_chanel"),medium:"",campaign:window.aiFunction.getURLParameter("id_campaign"),content:window.aiFunction.getURLParameter("id_landingpage"),term:window.aiFunction.getURLParameter("id"),type:"direct",time:(new Date).getTime(),checksum:""},f.checksum=_ea_utm_checksum(f),b=JSON2.stringify(f),e=!0;else{var d=window.aiFunction.getReferrerDomain(),
g=_antsGetDefaultCookieDomain(),u=_ea_get_utm();void 0!=d&&""!=d&&void 0!=g&&""!=g&&0>d.indexOf(g)||""==u.source&&void 0!=d&&""!=d?(f={source:d,medium:"",campaign:"",content:"",term:"",type:"refferrer",time:(new Date).getTime(),checksum:""},e=!0,f.checksum=_ea_utm_checksum(f),b=JSON2.stringify(f)):""!=d||(void 0==g||""==g||""!=u.source&&"refferrer"!=u.type)||(b="",e=!0)}if(e){var m=ants_encryptBase64(b);window.aiFunction.setCookie("_ants_utm_v2",m,15552E6,"/","",0);window.aiFunction.setCookie("_ants_utm",
"",0,"/","",0);"undefined"!==typeof Storage&&(e||b)&&(window.localStorage._ants_utm_v2=m,window.localStorage.removeItem("_ants_utm"))}}catch(x){}};_ea_save_utm();
var _ea_save_tup=function(b,e){try{if(void 0!=b&&""!=b&&0<e){var c={checksum:b+"-"+e,time:(new Date).getTime()},f=JSON2.stringify(c);key="_ants_tup_"+e;window.aiFunction.setCookie(key,f,864E5,"/","",0);"undefined"!==typeof Storage&&key&&localStorage.setItem(key,f)}}catch(d){}},_ea_get_tup=function(b){var e="";try{if(0>=b)return e;b="_ants_tup_"+b;var c="",f=window.aiFunction.getCookie(b);if(void 0!=f&&""!=f)c=JSON2.parse(f);else if("undefined"!==typeof Storage)try{if(f=localStorage.getItem(b),void 0!=
f&&""!=f){var c=JSON2.parse(f),d=c.time+864E5;(new Date).getTime()>d&&localStorage.setItem(b,"")}}catch(g){}""!=c&&(e=c.checksum)}catch(u){}return e};
